openapi: 3.1.0
info:
  title: Eversource Product Catalogue API
  description: API for suppliers to create a product catalogue entry in the Eversource system.
  version: 1.0.0
paths:
  /catalogue:
    post:
      summary: Create a new product catalogue entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customerNumber
                - authenticationCode
                - item
              properties:
                customerNumber:
                  type: string
                  description: ECOS Customer Number
                  example: "1234567890"
                authenticationCode:
                  type: string
                  description: ECOS Authentication Code
                  example: "authcode123456"
                item:
                  type: object
                  required:
                    - code
                    - description
                  properties:
                    code:
                      type: string
                      description: Supplier's item code
                      example: "87416"
                    description:
                      type: string
                      description: Supplier's item description
                      example: "CHERRIES IQF"
                    sizeDescription:
                      type: string
                      description: Supplier's item dimensions
                      example: "1 KG"
                    brand:
                      type: string
                      description: Supplier's item brand
                      example: "CATCHOICE"
                    unitOfMeasure:
                      type: string
                      description: Unit of measure for the item
                      example: "BAG"
                    category:
                      type: string
                      description: Catalogue Category Group
                      example: "B3718"
                    categoryDescription:
                      type: string
                      description: Catalogue Category Description
                      example: "FROZEN FRUIT"
                    taxRate:
                      type: number
                      format: float
                      description: Tax rate for the item
                      example: 0.0
                    price:
                      type: object
                      required:
                        - effectiveDate
                        - amount
                      properties:
                        effectiveDate:
                          type: string
                          description: Effective date of the price
                          example: "*CURRENT"
                        amount:
                          type: number
                          format: float
                          description: Price of the item
                          example: 10.71
                    quantityDescription:
                      type: string
                      description: Supplier's item quantity description
                      example: "50pk"
                    compatibleType:
                      type: string
                      description: Compatible type
                      example: "Laser Printer"
                    compatibleModels:
                      type: string
                      description: List of compatible models
                      example: "Stylus Colour 200"
                    extendedDescription:
                      type: string
                      description: Extended item description
                      example: "High-quality frozen cherries"
                    technicalSpecification:
                      type: string
                      description: Item technical specification
                      example: "Frozen at -18°C"
                    specificationURL:
                      type: string
                      description: URL to the manufacturer's technical specification
                      example: "http://example.com/spec"
                    specificationNotes:
                      type: string
                      description: Manufacturer's notes
                      example: "Best stored in a freezer"
                    unitOfMeasureDescription:
                      type: string
                      description: Long description for unit of measure
                      example: "Bag of 1 KG"
                    imageSmall:
                      type: string
                      description: Thumbnail image name
                      example: "cherries_small.jpg"
                    imageLarge:
                      type: string
                      description: Large image name
                      example: "cherries_large.jpg"
                    imagePDF:
                      type: string
                      description: PDF image name
                      example: "cherries.pdf"
                    brandLogo:
                      type: string
                      description: Brand logo image path
                      example: "catchoice.jpg"
                    leadTime:
                      type: integer
                      description: Lead time in days for shipping
                      example: 1
                    defaultWarehouse:
                      type: string
                      description: Default warehouse
                      example: "WH1"
                    stockOnHand:
                      type: integer
                      description: Current stock level
                      example: 100
                    outOfStockPolicy:
                      type: string
                      description: Out of stock policy
                      example: "0"
                    type:
                      type: string
                      description: Item type as defined by ECOS
                      example: "*INVENTORY"
                    weight:
                      type: number
                      format: float
                      description: Weight of item
                      example: 1.0
                    minimumOrderQuantity:
                      type: integer
                      description: Minimum order quantity
                      example: 1
                    maximumOrderQuantity:
                      type: integer
                      description: Maximum order quantity
                      example: 1000
                    lotSize:
                      type: integer
                      description: Minimum incremental amount that can be purchased
                      example: 1
                    priceList:
                      type: string
                      description: Price list code
                      example: "PL1"
                    currency:
                      type: string
                      description: Currency used for this item
                      example: "NZD"
      responses:
        "201":
          description: Product catalogue entry created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
